# Lesson 5

## 1)

In [14]:
import numpy as np
from datascience import *

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

In [16]:
#Create array with 4 string elements
Names=make_array('Ben', 'Thompson', 'Oregon', 'Blue')
Names

array(['Ben', 'Thompson', 'Oregon', 'Blue'], dtype='<U8')

In [19]:
#Make all elements uppercase
np.char.upper(Names)

array(['BEN', 'THOMPSON', 'OREGON', 'BLUE'], dtype='<U8')

In [49]:
#Count amount of times 'a' shows up in each element of array
np.char.count(Names,'a')

array([0, 0, 0, 0])

In [51]:
#use a numpy finction to find length of each element in array
mylen = np.vectorize(len)
print(mylen(Names))

[3 8 6 4]


## 2

In [34]:
#Create an array with every other odd number starting with 1 and ending with 41(including)
odds=np.arange(1,42,4)
odds

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [39]:
#use numpy to find the sum of all elements of this array
sum=np.sum(odds)
sum

231

In [42]:
#Use numpy to find the product of all elements of the array
prod=np.prod(odds.astype(float))
prod

7579867420125.0

In [47]:
#use numpy to find natural log of each element
ln=np.log(odds)
ln

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207])

In [48]:
#Use np.diff() to find the difference between all elements
np.diff(ln)

array([1.60943791, 0.58778666, 0.36772478, 0.26826399, 0.21130909,
       0.17435339, 0.14842001, 0.12921173, 0.11441035, 0.10265415])

In [46]:
#Find a way to perform the opposite of np.diff()
adj_sums=np.cumsum(ln)
adj_sums

array([ 0.        ,  1.60943791,  3.80666249,  6.37161185,  9.20482519,
       12.24934763, 15.46822345, 18.83551928, 22.33202685, 25.94294476,
       29.65651682])